name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.7'
          cache: false
      - name: test
        run: go test -v -race ./...
      - name: coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: 'false'
          chart: 'false'
          amend: 'true'
          go-version: '1.20.7'
        continue-on-error: true
